layout_spectrum: 0.7942875
typography_spectrum: 0.9176771
color:
  saturation: 0.3944951
  lightness: 0.8444489
  brandStrength: 0.06226187
  rhythmicContrast: 0.7742312
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Excellence in IT Consulting
